# -*- coding: utf-8 -*-
"""Практическая_работа_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/enikolaev/IT-and-Programming/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_02.ipynb

# Лабораторная работа 2. Управление ходом выполнения программы

## Задание

Необходимо вычислить значение выражения:
$$Z={1}-\frac{X}{2!}+\frac{Y^2}{3!}-\frac{X^3}{4!}+\frac{Y^4}{5!}-...$$
Для каждой переменной необходимо вывести ее значение и тип.

## Анализ выражения и определение переменных

Проанализируем выражение и определим переменные, которые потребуются для выполнения задания. Независимые переменные: $X, Y, N$. Переменная, которая должна быть вычислена на основе независимых: $Z$.

Следует обратить внимание, что в выражении неизвестное число слагаемых, поэтому необходимо ввести переменную $N$ для представления количества слагаемых.

Обратите внимание, что знаки слагаемых чередуются, а степени числителя и множетели знаменателя привязаны к порядковому номеру слагаемого.

## Вычисление выражение, печать результатов
"""



"""Код для вычисления значения выражения $Z$:"""

from math import factorial

X = 2
Y = 3
N = 10
print("X =", X, ", type(X) =", type(X))
print("Y =", Y, ", type(Y) =", type(Y))
print("N =", N, ", type(N) =", type(N))

Z = 1

for i in range(1, N + 1):
    if i % 2 == 1:
        chisl = X ** i
    else:
        chisl = Y ** i

    znam = factorial(i + 1)

    if i % 2 == 1:
        Z -= chisl / znam
    else:
        Z += chisl / znam

print("Z =", Z)
print("Type of Z:", type(Z))



"""Решите пример в соответствии с индивидуальным заданием"""

from math import factorial

X = 2
Y = 3
N = 10

Z = 1

for i in range(1, N + 1):
    if i % 2 == 1:
        chisl = X ** i
        Z -= chisl / factorial(i + 1)
    else:
        chisl = Y ** i
        Z += chisl / factorial(i + 1)

print(Z)