# -*- coding: utf-8 -*-
"""Практическая_работа_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/enikolaev/IT-and-Programming/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0_03.ipynb

# Лабораторная работа 3. Пользовательские функции

## Задание

Напишите функцию, которая по *трём переданным натуральным* числам возвращает, могут ли эти числа являться членами *арифметической прогрессии*.

Если «да», то функция возвращает **True**, в противном случае — **False**.

## Решение

### Объявление функции
"""

def is_arithmetic(a, b, c):
    numbers = sorted([a, b, c])
    return numbers[1] - numbers[0] == numbers[2] - numbers[1]

"""### Демонстрация использования функции"""

def is_arithmetic(a, b, c):
    numbers = sorted([a, b, c])
    return numbers[1] - numbers[0] == numbers[2] - numbers[1]
x, y, z = 2, 4, 6
print(f'Числа {x}, {y}, {z} являются членами арифметической прогрессии: {is_arithmetic(x, y, z)}')

x, y, z = 3, 7, 10
print(f'Числа {x}, {y}, {z} являются членами арифметической прогрессии: {is_arithmetic(x, y, z)}')

x, y, z = 15, 10, 5
print(f'Числа {x}, {y}, {z} являются членами арифметической прогрессии: {is_arithmetic(x, y, z)}')

"""Решите пример в соответствии с индивидуальным заданием"""

def is_arithmetic(a, b, c):
    numbers = sorted([a, b, c])
    return numbers[1] - numbers[0] == numbers[2] - numbers[1]


x, y, z = 2, 4, 6
print(f'Числа {x}, {y}, {z}: {is_arithmetic(x, y, z)}')

x, y, z = 3, 7, 10
print(f'Числа {x}, {y}, {z}: {is_arithmetic(x, y, z)}')

x, y, z = 15, 10, 5
print(f'Числа {x}, {y}, {z}: {is_arithmetic(x, y, z)}')